services:
  minio-upload-api:
    build: .
    container_name: minio-upload-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - airflow-n8n-net
    restart: unless-stopped

networks:
  airflow-n8n-net:
    external: true                          
